apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - name: http
    port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30032
