apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todoapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80